import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "News App Frontend",
  description: "Generated by Semih Şahinoğlu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
